import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '../../chatgpt-auth';
import {z} from 'zod';
import {provinces,locationOf} from '../../../lib/locations';
const schema=z.object({id:z.string().uuid(),groupId:z.string().uuid().nullable().optional(),provider:z.enum(['gas','agua','luz','rentas','municipio','comercio','otras','personalizado']),account:z.string().trim().min(1).max(80),property:z.string().trim().min(1).max(160),province:z.string().refine(p=>provinces.includes(p),"Elegí una provincia válida."),city:z.string().trim().min(1,"Ingresá una ciudad.").max(100),providerName:z.string().trim().max(160).optional(),checked:z.string().date().optional(),total:z.number().finite().min(0).max(1e12).optional(),note:z.string().max(3000).optional(),bills:z.array(z.object({number:z.string().trim().min(1).max(120),period:z.string().trim().min(1).max(80),due:z.string().date(),amount:z.number().finite().min(0).max(1e12),overdue:z.boolean().optional()})).max(200)}).refine(s=>s.provider!=='personalizado'||!!s.providerName,'Indicá el nombre del prestador u organismo.').refine(s=>s.provider!=='gas'||/^\d{17}$/.test(s.account),'La cuenta de Camuzzi debe tener 17 dígitos.');
export async function GET(){const user=await getChatGPTUser();if(!user)return Response.json({error:'Ingresá con ChatGPT para acceder a tus suministros.'},{status:401});try{if(!env.DB)throw Error('DB');const r=await env.DB.prepare('SELECT data FROM supplies WHERE owner = ?').bind(user.userId).all<{data:string}>();return Response.json(r.results.map(x=>{const data=JSON.parse(x.data);return {...data,...locationOf(data)}}),{headers:{'Cache-Control':'no-store'}})}catch{return Response.json({error:'No se pudo cargar la información. Reintentá en unos momentos.'},{status:503})}}
export async function POST(request:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:'Ingresá con ChatGPT para guardar.'},{status:401});if(request.headers.get('origin')!==new URL(request.url).origin)return Response.json({error:'Origen no permitido.'},{status:403});let raw;try{const body=await request.text();if(body.length>100000)return Response.json({error:'Demasiados datos.'},{status:413});raw=JSON.parse(body)}catch{return Response.json({error:'Datos inválidos.'},{status:400})}const parsed=schema.safeParse(raw);if(!parsed.success)return Response.json({error:parsed.error.issues[0]?.message||'Revisá los datos.'},{status:400});try{if(!env.DB)throw Error('DB');const s=parsed.data;if(s.groupId){const group=await env.DB.prepare('SELECT id FROM dossiers WHERE id=? AND owner=?').bind(s.groupId,user.userId).first();if(!group)return Response.json({error:'Elegí una propiedad propio válido.'},{status:400})}const prior=await env.DB.prepare('SELECT owner FROM supplies WHERE id = ?').bind(s.id).first<{owner:string}>();if(prior&&prior.owner!==user.userId)return Response.json({error:'Registro no disponible.'},{status:403});await env.DB.prepare('INSERT INTO supplies (id,owner,data) VALUES (?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data WHERE supplies.owner=excluded.owner').bind(s.id,user.userId,JSON.stringify(s)).run();return Response.json(s)}catch{return Response.json({error:'No se pudo guardar. Tus datos siguen en el formulario; reintentá.'},{status:503})}}




export async function DELETE(request:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:'Ingresá para continuar.'},{status:401});if(request.headers.get('origin')!==new URL(request.url).origin)return Response.json({error:'Origen no permitido.'},{status:403});try{if(!env.DB)throw Error('DB');const raw=await request.json();const parsed=z.object({id:z.string().uuid()}).safeParse(raw);if(!parsed.success)return Response.json({error:'Suministro inválido.'},{status:400});await env.DB.prepare('DELETE FROM supplies WHERE id=? AND owner=?').bind(parsed.data.id,user.userId).run();return Response.json({ok:true})}catch{return Response.json({error:'No se pudo dar de baja el suministro.'},{status:503})}}

