import type {ReportBill} from './report-types';

const base='https://tramites.edersa.com.ar/OFICINA_VIRTUAL_PROD_EDERSA/servlet/';
type State=Record<string,any>;
export class EdersaError extends Error {}
function decode(s:string){return s.replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n))).replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&')}
function state(s:string):State{const match=s.match(/name="GXState"\s+value=(['"])([\s\S]*?)\1/);if(!match)throw new EdersaError('EdERSA cambió la respuesta del portal. No se confirmó la deuda.');return JSON.parse(decode(match[2]))}
function safeUrl(value:string,relative?:string){const u=new URL(value,relative);if(u.protocol!=='https:'||!['tramites.edersa.com.ar','pagos.edersa.com.ar'].includes(u.hostname)||u.username||u.password||u.port&&u.port!=='443')throw new EdersaError('EdERSA devolvió un enlace no reconocido.');return u}
// One independent cookie jar per consultation; no sessions or credentials reach the client.
class Session{
 cookies=new Map<string,{host:string;path:string;name:string;value:string}>();
 async request(value:string,init:RequestInit={}):Promise<{url:string;bytes:Uint8Array;text:string}>{let url=safeUrl(value);for(let hop=0;hop<8;hop++){
  const headers=new Headers(init.headers);const cookies=[...this.cookies.values()].filter(c=>c.host===url.hostname&&(url.pathname===c.path||url.pathname.startsWith(c.path.endsWith('/')?c.path:c.path+'/')));if(cookies.length)headers.set('Cookie',cookies.map(c=>c.name+'='+c.value).join('; '));
  const response=await fetch(url,{...init,headers,redirect:'manual',signal:AbortSignal.timeout(60000)});
  for(const raw of response.headers.getSetCookie()){const [pair,...attrs]=raw.split(';');const at=pair.indexOf('=');const name=pair.slice(0,at).trim();const path=attrs.find(a=>a.trim().toLowerCase().startsWith('path='))?.trim().slice(5)||url.pathname.slice(0,url.pathname.lastIndexOf('/')+1);if(at>0)this.cookies.set(url.hostname+'|'+path+'|'+name,{host:url.hostname,path,name,value:pair.slice(at+1)});}
  if([301,302,303,307,308].includes(response.status)){const next=response.headers.get('location');await response.body?.cancel();if(!next)throw Error('redirect');url=safeUrl(next,url.href);if([301,302,303].includes(response.status))init={method:'GET'};continue}
  if(!response.ok){await response.body?.cancel();throw new EdersaError('EdERSA no respondió a la consulta (HTTP '+response.status+'). Reintentá.');}
  const reader=response.body?.getReader();const chunks:Uint8Array[]=[];let length=0;if(reader)while(true){const r=await reader.read();if(r.done)break;length+=r.value.length;if(length>24_000_000){await reader.cancel();throw Error('response too large')}chunks.push(r.value)}const bytes=new Uint8Array(length);let pos=0;for(const c of chunks){bytes.set(c,pos);pos+=c.length}return {url:url.href,bytes,text:new TextDecoder().decode(bytes)};
 }throw new EdersaError('EdERSA no pudo completar el ingreso.');}
 async form(url:string,g:State,event:string,fields:Record<string,string>={}){return this.request(url,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({...fields,GXState:JSON.stringify({...g,_EventName:event}),_EventName:event}).toString()})}
 async event(url:string,g:State,obj:string,pkg:string,event:string,parms:unknown[],hashed:string[]=[]){const result=await this.request(url.split('?')[0]+'?gxfullajaxEvt',{method:'POST',headers:{'Content-Type':'application/json','GxAjaxRequest':'1','X-GXAUTH-TOKEN':g['GX_AUTH_'+obj.toUpperCase()]||''},body:JSON.stringify({MPage:false,cmpCtx:'',parms,hsh:hashed.map(k=>({hsh:g['gxhash_'+k],row:''})),objClass:obj,pkgName:pkg,events:[event],grids:{}})});return JSON.parse(result.text) as State}
}
function redirect(j:State,from:string){const value=j.gxCommands?.find((c:State)=>c.redirect?.url)?.redirect.url;if(typeof value!=='string')throw new EdersaError('EdERSA no habilitó la consulta o descarga solicitada.');return safeUrl(value,from).href}
function amount(s:unknown){const value=String(s??'').replace(/[$\s]/g,'');if(!/^-?\d+(?:\.\d{1,2})?$/.test(value))throw new EdersaError('EdERSA devolvió un importe no reconocido.');return Number(value)}
function date(s:string){const m=s.trim().match(/^(\d{2})\/(\d{2})\/(\d{2}|\d{4})$/);if(!m)throw new EdersaError('EdERSA devolvió una fecha no reconocida.');return (m[3].length===2?'20':'')+m[3]+'-'+m[2]+'-'+m[1]}
export function parseEdersa(raw:State,account:string){
 const data=raw.vSALWSCONSULTAFACTURAS;if(!data||!Array.isArray(data.Facturas))throw new EdersaError('EdERSA no confirmó las facturas.');
 const identity=String(data.TextoEncabezado).match(/Cliente:\s*(\d+)\s*\/\s*(\d+)/i);if(!identity||'9'+identity[1]+identity[2].padStart(4,'0')!==account)throw new EdersaError('El suministro informado por EdERSA no coincide con el NIS solicitado.');
 const summary=String(data.TextoPie).match(/comprobantes adeudados:\s*(\d+)\s*-\s*Importe Adeudado:\s*\$\s*([\d.]+)/i);if(!summary)throw new EdersaError('EdERSA no confirmó el total adeudado.');
 const originals=new Map<string,string>();const bills:ReportBill[]=[];
 for(const invoice of data.Facturas){const fields:Record<string,string>={};for(let i=1;i<=18;i++)fields[String(invoice['Campo'+i+'Titulo']||'').trim().toLowerCase()]=String(invoice['Campo'+i+'Valor']||'').trim();const balance=amount(fields.saldo);if(balance<=0)continue;if(fields.pagado==='S'||fields.estado?.toLowerCase()==='pagado')throw new EdersaError('EdERSA devolvió un saldo contradictorio.');const number=fields.comprobante;if(!number||!invoice.Identificador||originals.has(number))throw new EdersaError('EdERSA devolvió comprobantes ambiguos.');const due=date(fields['fecha vto']);bills.push({number,period:date(fields.fecha).slice(0,7),due,amount:balance,overdue:due<new Date().toISOString().slice(0,10)});originals.set(number,invoice.Identificador)}
 const total=Math.round(bills.reduce((n,b)=>n+b.amount,0)*100)/100;if(bills.length!==Number(summary[1])||Math.abs(total-amount(summary[2]))>0.01)throw new EdersaError('El detalle de EdERSA no coincide con su total. No se confirmó la consulta.');
 return {bills,total,originals,checked:new Date().toLocaleDateString('en-CA',{timeZone:'America/Argentina/Buenos_Aires'}),note:'Consulta automática de EdERSA. '+(total===0?'No tiene deuda pendiente. ':'Se muestran los comprobantes con saldo pendiente. ')+String(data.TextoEncabezado).split('\n').filter((s:string)=>/desde/i.test(s)).join(' ')};
}
export async function consultEdersa(account:string,credentials:{email?:string;password?:string},progress: (percent:number,label:string)=>Promise<void>=async()=>{}){
 if(!/^9\d{10}$/.test(account))throw new EdersaError('El NIS de EdERSA debe tener 11 dígitos y comenzar con 9. Corregilo en Editar suministro.');if(!credentials.email||!credentials.password)throw new EdersaError('Falta configurar la cuenta de EdERSA en el servidor.');
 const session=new Session();await progress(10,'Ingresando a EdERSA');let page=await session.request(base+'com.oficinavirtual.login');page=await session.form(page.url,state(page.text),'EENTER.',{vUSUARIO:credentials.email,vPASSWORD:credentials.password});if(!page.url.includes('wwpbaseobjects.home'))throw new EdersaError('EdERSA rechazó el ingreso. Revisá la cuenta, la clave y su activación.');
 await progress(30,'Verificando NIS '+account);let accounts=await session.request(base+'com.oficinavirtual.usuariocuentas?AsociarCuenta');let g=state(accounts.text);const find=()=>Array.isArray(g.vCUENTASDT)?g.vCUENTASDT.find((a:State)=>'9'+a.PerNro+String(a.CtaNro).padStart(4,'0')===account):undefined;let selected=find();
 if(!selected){await progress(40,'Asociando NIS '+account);await session.form(accounts.url,g,"E'DOAGREGAR'.",{vPERNUMPER:account});accounts=await session.request(base+'com.oficinavirtual.usuariocuentas?AsociarCuenta');g=state(accounts.text);selected=find();if(!selected)throw new EdersaError('EdERSA no permitió asociar este NIS. Verificá el número o los datos adicionales que solicita el portal.');}
 page=await session.request(base+'com.oficinavirtual.cuentaactual?'+encodeURIComponent(JSON.stringify(selected)));if(!page.url.includes('wwpbaseobjects.home'))page=await session.request(base+'com.oficinavirtual.wwpbaseobjects.home');g=state(page.text);const current=g.vCUENTASDTACTUAL;if(!current||Number(current.PerNro)!==Number(selected.PerNro)||Number(current.CtaNro)!==Number(selected.CtaNro))throw new EdersaError('EdERSA no confirmó la selección del NIS.');
 await progress(60,'Consultando facturas de '+account);const command=await session.event(page.url,g,'wwpbaseobjects.home','com.oficinavirtual','MOREINFOCARD4CAPTION.CLICK',['vCUENTASDTACTUAL','vCONTEXTO','vPGMNAME','vSDTSOLICITAINGRESO'].map(k=>g[k]??''));page=await session.request(redirect(command,page.url));g=state(page.text);const parsed=parseEdersa(g,account);await progress(85,'Verificando el detalle de '+account);
 return {...parsed,async download(numbers:string[],budget=12_000_000){const files:{number:string;bytes:Uint8Array}[]=[];const missing:{number:string;reason:string}[]=[];for(const number of numbers){try{const ident=parsed.originals.get(number);if(!ident)throw Error();const j=await session.event(page.url,g,'edersa.rwdhomemaster','com.portalclientes','VIMPRIMIRFACTURA.CLICK',[ident]);const pdf=await session.request(redirect(j,page.url));if(new TextDecoder().decode(pdf.bytes.slice(0,5))!=='%PDF-'||pdf.bytes.length>budget)throw Error();budget-=pdf.bytes.length;files.push({number,bytes:pdf.bytes})}catch{missing.push({number,reason:'No se pudo descargar la boleta original de EdERSA. Reintentá.'})}}return {files,missing}}};
}
